### ISSUE TITLE
Adding random orders while orders from file are still being added stops further orders from file being added to the queue

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#155]
If you try adding random orders right after program starts you can see that no further orders from the file are being added

**Comment by trz-maier** [comment]
This is now kind of fixed but random orders get added and pushed to the end of the queue - is this expected behaviour or another bug?

**Comment by jathanasiou** [comment]
Because of the sorting implemented for Order objects, they are placed in the queue depending on two criterias

1. Priority
2. Then, creation time/order of the instance. Older instances go first.

https://github.com/trz-maier/hwu-ase-group3/blob/0e2b52259458bb6f2cdef978ce140ce31812a2e9/src/ase/cw/model/Order.java#L120-L132

In sort, this works as expected and it was a choice taken during the implementation, though could be easily changed if desired.

**Comment by trz-maier** [comment]
I don't think this is related. I am talking about orders of the same priority *not* being sorted by the time they are added when both randomly generated orders and orders from file are simultaneously added to the queues

**Comment by Orangefruit2** [comment]
we can use the Date timestamp to sort. Instead of adding the timestamp, as soon as the order is taken by the server, we can add a timestamp -as previously - when we create the order

**Comment by trz-maier** [comment]
Can we not set a date or counter of Order being added to the queue as opposed to object being created? This sounds like a simple solution

**Comment by Orangefruit2** [comment]
a function like setCounter would work, but would be a bit hacky, since you can not guarantee that you always set the counter.
Using the timestamp again when the object is created(as in CW1) should be fine, since the date is mandatory. But the cw requirements don't tell us that we have to set the date when the server finishes the order.
But i am fine with both Solutions.

**Comment by trz-maier** [comment]
moved to #160
