### ISSUE TITLE
create a String representation of the bill

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#49]
Something like this....

![image](https://user-images.githubusercontent.com/46493724/52975991-9ac6ca00-33bf-11e9-9b00-66241ee9c38c.png)

**Comment by jathanasiou** [comment]
I think that this representation does not _need to_ be in `toString()` method, unlike #48 , where it is needed because of how `JList` works.

So, question: wouldn't it be better to have this in a `getAsciiDisplay()` or something similar in case we need to use the `toString` for something else later? It is often needed by various collections/libraries.

**Comment by trz-maier** [comment]
yes, good idea. I did not mean to overload `toString()` but whichever name you choose it should return type String to be inserted into the JText area
